### ISSUE TITLE
`rush init-project` would encounter error "Option moduleResolution" must be set to Node 16 xxx" if npm/pnpm have not install typescirpt globally

### ISSUE THREAD

**Issue by betterRunner** [tiktok/rush-plugins#11]
Hi there we encounter an error while running `rush init-project` command:

![img_v3_027i_0a75c9c5-053e-4a5d-b1cd-88ac71f7b2ag](https://github.com/tiktok/rush-plugins/assets/7123136/ab1927b1-bdd2-4c52-9cec-53303b22d87d)

After installing typescript globally `pnpm install -g typescript` it is fixed, any idea about what cause this problem?

**Comment by betterRunner** [comment]
Some colleagues would still encounter it even have run `pnpm install -g typescript`, very strange issue.  
- node version: 18.19.0
- @microsoft/rush: 5.112.1
- typescript: 5.3.3

**Comment by chengcyber** [comment]
Hi betterRunner, thanks for reaching out to us! We have recevied a similar issue before at https://github.com/tiktok/rush-plugins/issues/7

Could you give the `rush-init-project-plugin@0.10.2` a try? I believe this version fixes the issue since it released with a beta version of `ts-node` that targets Node.js 18 & 20.
